douban_movie/urls.py
from django.urls import path
from douban_movie.views import index, movie_detail, search_movie, to_search_list

app_name = 'douban_movie'

urlpatterns = [
	path('', index, name='index'),
	path('movie_detail', movie_detail, name='movie_detail'),
	path('movie_detail/<str:id>', movie_detail, name='movie_detail'),
	path('search_movie', search_movie, name='search_movie'),
	path('to_search_list', to_search_list, name='to_search_list'),

]

movie/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
	path('admin/', admin.site.urls),
	path('navigation/', include('navigation.urls')),
	path('douban_movie/', include('douban_movie.urls')),
	path('user/', include('user.urls')),
	path('comments/', include('django_comments.urls'))
]

user/urls.py
from django.urls import path
from user.views import to_register, register, to_login, login, logout

app_name = 'user'

urlpatterns = [
	path('to_register', to_register, name='to_register'),
	path('register', register, name='register'),
	path('to_login', to_login, name='to_login'),
	path('login', login, name='login'),
    path('logout', logout, name='logout')
]

douban_movie/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from utils.make_query import make_page
from utils.base_model import BaseModel

# Create your models here.
class DoubanMovie(BaseModel, models.Model):

	id = models.CharField(_('主键ID'), max_length=32, primary_key=True, blank=False)
	douban_movie_id = models.CharField(_('豆瓣电影ID'), max_length=100, blank=False, default='')
	title = models.CharField(_('电影标题'), max_length=500, blank=False, default='')
	cover = models.CharField(_('电影封面图片地址'), max_length=500, blank=True)
	directors = models.CharField(_('导演，多个导演之间用/分割'), max_length=500, blank=True)
	writers = models.CharField(_('编剧，多个编剧之间用/分割'), max_length=500, blank=True)
	actors = models.CharField(_('主演，多个主演之间用/分割'), max_length=2000, blank=True)
	type = models.CharField(_('类型，多个类型之间用/分割'), max_length=500, blank=True)
	area = models.CharField(_('制片国家/地区'), max_length=500, blank=True)
	lang = models.CharField(_('语言'), max_length=100, blank=True)
	release_date = models.DateField(_('上映日期。多个上映日期则选择最新的上映日期'), blank=True, null=True)
	runtime = models.IntegerField(_('片长（分钟）'), blank=True, null=True)
	imdb = models.CharField(_('imdb链接'), max_length=100, blank=True)
	rate = models.FloatField(_('电影评分'), blank=True, null=True)
	votes = models.IntegerField(_('电影评分投票人数'), blank=True, null=True)
	summary = models.CharField(_('电影简介'), max_length=2000, blank=True)

	class Meta:
		db_table = 't_douban_movie'

	def get_conditions(search_key=''):

		filter_by = 'title contains "{search_key}" || actors contains "{search_key}"'.format(search_key=search_key) if search_key else ''

		types = DoubanMovie.get_distinct_with_split('type', '/', filter_by=filter_by, compute_count=True, return_sorted_list=True)
		langs = DoubanMovie.get_distinct_with_split('lang', '/', filter_by=filter_by, compute_count=True, return_sorted_list=True)

		return types, langs

douban_movie/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.http import HttpResponse, JsonResponse, Http404

from user.decorators import check_login
from douban_movie.models import DoubanMovie
from datetime import date

# Create your views here.

@check_login()
@require_GET
def index(request):

	today = date.today()
	y, m, d = today.year, today.month, today.day

	filter_by = 'release_date > date({last_year},{month},{day}) && ~votes = None && ~rate = None'.format(
		last_year = y - 1,
		month = m,
		day = d
	)
	order_by = 'votes desc, rate desc'

	_,data =  DoubanMovie.make_page(filter_by, order_by, page=1, limit=5, compute_count=False)

	context = {
		'movies' : data
	}

	return render(request, 'douban_movie/index.html', context)


@require_GET
def movie_detail(request, id):
	if not id:
		raise Http404('电影id不可为空')

	filter_by = 'id == "%s"'%str(id)
	_, data = DoubanMovie.make_page(filter_by=filter_by, limit=1, page=1, compute_count=False, to_serializable=True)

	data = data[0] if len(data)>0 else {}

	return render(request, 'douban_movie/movie_detail.html', {
		'movie' : data
	})

@require_GET
def to_search_list(request):

	search_key = request.GET.get('search_key', '')

	context = {'search_key' : search_key} if search_key else None

	return render(request, 'douban_movie/search_list.html', context)

@require_GET
def search_movie(request):
	args = request.GET
	search_key = args.get('search_key', '')
	page = int(args.get('page', 1))
	limit = int(args.get('limit', 20))
	order_by = args.get('order_by', 'release_date desc')

	filter_by = 'title contains "{search_key}" || actors contains "{search_key}"'.format(search_key=search_key) if search_key else None

	count, data = DoubanMovie.make_page(filter_by, order_by, page=page, limit=limit, to_serializable=True, compute_count=True)

	types, langs = DoubanMovie.get_conditions(search_key)

	context = {
		'npage' : count//limit + (1 if count%limit!=0 else 0),
		'page' : page,
		'movies' : data,
		'conditions' : {
			'types' : types,
			'langs' : langs
		}
	}
	return render(request, 'douban_movie/search_list.html', context)

templates/douban_movie/index.html
{% extends 'douban_movie/template.html' %}

{% block title %}首页{% endblock %}


{% block body %}
{{ block.super }}
{% load douban_movie_tags %}

<div id="carouselHotMovie" class="carousel slide" data-ride="carousel">		
	<ol class="carousel-indicators">
		{% for movie in movies %}
			<li data-target="#carouselHotMovie" data-slide-to={{ forloop.counter0 }} {% if forloop.first %}class="active"{% endif %}></li>
		{% endfor %}
	</ol>
	<div class="carousel-inner">
		{% if movies %}
			{% for movie in movies %}
				<div class="carousel-item {% if forloop.first %}active{% endif %}">
					<div class="container">
						<div class="row movie-info">
							<div class="col col-md-8">
								<h1 class="movie-title">{{movie.title}}</h1>
								<div class="movie-summary">
									<span class="movie-summary-leading ion-md-quote"></span>
									<div class="movie-summary-paragraph-container">
										{% for summary_paragraph in movie.summary|split:'\n' %}
											<p class="movie-summary-paragraph">
												{{summary_paragraph}}
											</p>
										{% endfor %}
									</div>
								</div>
							</div>
							<div class="movie-cover col col-md-4" onclick="window.location.href='{% url 'douban_movie:movie_detail' movie.id %}'">
								<img src="https://images.weserv.nl/?url={{ movie.cover|replace:'http://'|replace:'https://' }}">
							</div>
						</div>
					</div>
				</div>
			{% endfor %}
		{% endif %}
	</div>
	<a class="carousel-control-prev col col-md-1" href="#carouselHotMovie" role="button" data-slide="prev">
		<span class="carousel-control-prev-icon" aria-hidden="true"></span>
		<span class="sr-only">上一个</span>
	</a>
	<a class="carousel-control-next col col-md-1" href="#carouselHotMovie" role="button" data-slide="next">
		<span class="carousel-control-next-icon" aria-hidden="true"></span>
		<span class="sr-only">下一个</span>
	</a>
</div>


{% endblock %}

templates/douban_movie/movie_detail.html
{% extends 'douban_movie/template.html' %}

{% block title %}{{movie.title}}{% endblock %}


{% block body %}
	{{ block.super }}
	{% load douban_movie_tags %}

	{% for field,value in movie.items %}
		<p>{{field}}:{{value}}</p>
	{% endfor %}


{% endblock %}

templates/douban_movie/search_list.html
{% extends 'douban_movie/template.html' %}

{% block title %}{{search_key}}{% endblock %}


{% block body %}
	{% load douban_movie_tags %}
	{{ block.super }}

	<div id="conditions">
		<div class="condition-type">
			{% for type,count in conditions.types %}
				<a class="conditions-type-tag" href="#">{{type}}</a>
			{% endfor %}
		</div>
		<div class="condition-lang">
			{% for lang,count in conditions.langs %}
				<a class="conditions-lang-tag" href="#">{{lang}}</a>
			{% endfor %}
		</div>
	</div>

	<div id="movie_list">
		{% for movie in movies %}
			<div class="movie-info" onclick="to_movie_detail('{{movie.id}}')">
				<div class="movie-title">
					<p>标题：{{movie.title}}</p>
				</div>
				<div class="movie-type">
					<p>类型：{{movie.type}}</p>
				</div>
				<div class="movie-rate">
					<p>评分：{{movie.rate}}</p>
				</div>
				<div class="movie-votes">
					<p>评分人数：{{movie.votes}}</p>
				</div>
				<div class="movie-actors">
					<p>演员：{{movie.actors}}</p>
				</div>
				<div class="movie-summary">
					<p>简介：{{movie.summary}}</p>
				</div>
			</div>

		{% endfor %}
	</div>

	<div class="pagination-container">
		<nav>
			<ul class="pagination">
				<li class="page-item disabled">
					<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
				</li>
				{% for i in npage|myrange %}
					{% if page == i+1 %}
					{% else %}
						<li class="page-item"><a class="page-link" href="#">{{i|add:1}}</a></li>
					{% endif %}
				{%  endfor %}
				<li class="page-item">
					<a class="page-link" href="#">Next</a>
				</li>
			</ul>
		</nav>
	</div>


{% endblock %}

templates/douban_movie/template.html
{% extends 'common/template.html' %}

{% block head %}
	{% load staticfiles%}
	<link rel="stylesheet" type="text/css" href="{% static 'css/douban_movie/index.css' %}">
	<script type="text/javascript" src="{% static 'js/douban_movie/index.js' %}"></script>

{% endblock %}
	

{% block body %}
	<input type="hidden" id="douban_movie_index_url" value="{% url 'douban_movie:index' %}">
	<input type="hidden" id="douban_movie_movie_detail_url" value="{% url 'douban_movie:movie_detail' %}">
	<input type="hidden" id="douban_movie_to_search_list_url" value="{% url 'douban_movie:to_search_list' %}">
	<input type="hidden" id="douban_movie_search_movie_url" value="{% url 'douban_movie:search_movie' %}">
{% endblock %}