douban_movie/urls.py
from django.urls import path
from douban_movie.views import index, movie_detail, search_movie, to_search_list

app_name = 'douban_movie'

urlpatterns = [
	path('', index, name='index'),
	path('movie_detail', movie_detail, name='movie_detail'),
	path('movie_detail/<str:id>', movie_detail, name='movie_detail'),
	path('search_movie', search_movie, name='search_movie'),
	path('to_search_list', to_search_list, name='to_search_list'),

]

movie/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
	path('admin/', admin.site.urls),
	path('navigation/', include('navigation.urls')),
	path('douban_movie/', include('douban_movie.urls')),
	path('user/', include('user.urls')),
	path('comments/', include('django_comments.urls'))
]

navigation/urls.py
from django.urls import path
from navigation.views import get_navigation

app_name = 'navigation'

urlpatterns = [
	path('get_navigation', get_navigation, name='get_navigation')
]

user/urls.py
from django.urls import path
from user.views import to_register, register, to_login, login, logout

app_name = 'user'

urlpatterns = [
	path('to_register', to_register, name='to_register'),
	path('register', register, name='register'),
	path('to_login', to_login, name='to_login'),
	path('login', login, name='login'),
    path('logout', logout, name='logout')
]

navigation/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _

from utils.make_query import make_page
from utils.base_model import BaseModel

# Create your models here.
class Navigation(models.Model, BaseModel):

	id = models.CharField(_('主键ID'), max_length=32, primary_key=True, blank=False, default='')
	name = models.CharField(_('栏目名称'), max_length=100,  blank=False)
	parentid = models.CharField(_('父栏目ID'), max_length=32,  blank=True)
	ismenu = models.BooleanField(_('是否为菜单（栏目将显示在网站导航条中)'), blank=False)
	level = models.PositiveSmallIntegerField(_('层级'), blank=False)
	order = models.PositiveSmallIntegerField(_('层级内的顺序（正序）'), blank=False)
	url = models.CharField(_('栏目的url（注意该url为app:name格式，如user:login）'), max_length=100, blank=True)

	class Meta:
		db_table = 't_navigation'

navigation/views.py
from django.shortcuts import render

from navigation.models import Navigation
from django.http import JsonResponse

# Create your views here.
def get_navigation(request):
	return JsonResponse(Navigation.make_tree(filter_by='ismenu = True', order_by='level	,order'), safe=False, json_dumps_params={'ensure_ascii':False})

templates/common/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand ion-md-thumbs-up" href="{% url 'douban_movie:index' %}">Movie</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">

		<ul class="navbar-nav mr-auto" id="navigation">

		</ul>
		<form class="form-inline my-2 my-lg-0" id="search_movie_form" action="{% url 'douban_movie:search_movie' %}" method="get">
			<input class="form-control mr-sm-2" type="search" name="search_key" value="{{search_key}}" placeholder="{% if search_key %}{{search_key}}{% else %}搜索影片{% endif %}" aria-label="Search">
			<button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="border: 0px" onclick="search_movie()">
				<span class="oi oi-magnifying-glass"></span>
			</button>
		</form>
		{% if user.is_authenticated%}
			<ul class="navbar-nav">
				<li class="nav-item dropdown">
					<a class="nav-link " href="#"  data-toggle="dropdown" id="user-options" aria-haspopup="true" aria-expanded="false">
						{{user.username}}
					</a>
					<div class="dropdown-menu" aria-labelledby="user-options">
						<a class="dropdown-item" href="#">个人信息</a>
						<a class="dropdown-item" href="{% url 'user:logout' %}">退出</a>
					</div>
				</li>
			</ul>
		{% else %}
			<ul class="navbar-nav">
				<li class="nav-item">
					<a class="nav-link " href="{% url 'user:to_register' %}">注册</a>
				</li>
				<li class="nav-item">
					<a class="nav-link " href="{% url 'user:to_login' %}">登录</a>
				</li>
			</ul>
		{% endif %}
	</div>
</nav>

templates/common/modal.html
<div id="modal-template">
	<div class="modal fade" id="{modal_id}" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<h5 class="modal-title">{modal_title}</h5>
					<button type="button" class="close" data-dismiss="modal" aria-label="Close">
						<span aria-hidden="true">&times;</span>
					</button>
				</div>
				<div class="modal-body">
					{modal_body}
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-primary" data-dismiss="modal">关闭</button>
				</div>
			</div>
		</div>
	</div>
</div>

templates/common/navigation.html
<script type="text/html" id="generate_dropmenu">
	<%	for(var node_index in nodes){ %>
	<%		if(nodes[node_index].children){ %>
				<div class="dropdown dropright dropdown-submenu">
					<button class="dropdown-item dropdown-toggle" type="button" data-toggle="dropdown" data-hover="dropdown"><%= nodes[node_index].name %></button>
					<div class="dropdown-menu">
	<%					include('generate_dropmenu', {'nodes': nodes[node_index].children, 'url_map':url_map}) %>
					</div>
				</div>
	<%		}else{ %>
				<a class="dropdown-item" href="<%= nodes[node_index].url?url_map[nodes[node_index].url]:'#' %>"><%= nodes[node_index].name %></a>
	<%		} %>
	<%	} %>


</script>


<script type="text/html" id="generate_nav">
	<%	for(var node_index in nodes){ %>
	<%		if(nodes[node_index].children){ %>
				<li class="nav-item dropdown">
					<a class="nav-link dropdown-toggle" href="<%= nodes[node_index].url?url_map[nodes[node_index].url]:'#' %>" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" data-hover="dropdown"><%= nodes[node_index].name %></a>
					<div class="dropdown-menu">
	<%					include('generate_dropmenu', {'nodes': nodes[node_index].children, 'url_map':url_map}) %>
					</div>
				</li>
	<%		}else{ %>
				<li class="nav-item">
					<a class="nav-link" href="<%= nodes[node_index].url?url_map[nodes[node_index].url]:'#' %>"><%= nodes[node_index].name %></a>
				</li>
	<%		} %>
	<%	} %>
</script>

templates/common/pagination.html
<script type="text/html">

	<nav>
		<ul class="pagination">
			<li class="page-item disabled">
				<a class="page-link" href="#" tabindex="-1" aria-disabled="true">Previous</a>
			</li>
			<li class="page-item"><a class="page-link" href="#">1</a></li>
			<li class="page-item active" aria-current="page">
				<a class="page-link" href="#">2 <span class="sr-only">(current)</span></a>
			</li>
			<li class="page-item"><a class="page-link" href="#">3</a></li>
			<li class="page-item">
				<a class="page-link" href="#">Next</a>
			</li>
		</ul>
	</nav>
</script>

templates/common/template.html
<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}{% endblock %}</title>
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/common/bootstrap/bootstrap.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/common/bootstrap/bootstrap-submenu.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/common/open-iconic-bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/common/ionicons.css' %}">

	<script type="text/javascript" src="{% static 'js/common/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/common/popper.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/common/bootstrap/bootstrap.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/common/bootstrap/bootstrap-submenu.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/common/bootstrap/bootstrap-hover-dropdown.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/common/navigation.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/common/modal.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/common/template-web.js' %}"></script>


	{% block head %}{% endblock %}


</head>
<body>

		
	{% include "common/header.html" %}
	{% include "common/navigation.html" %}

	{% block body %}{% endblock %}

	{% include "common/modal.html" %}

	<script type="text/javascript">

		var url_map = {
			{% for navigation_url in navigation_urls %}
				'{{navigation_url}}' : '{% url navigation_url %}',
			{% endfor %}
		}
		function load_navigation(){
			$.ajax({
				async : true,
				type : 'get',
				url : "{% url 'navigation:get_navigation' %}",
				dataType : 'json',
				success : function(data){
					
					var nav_html = template('generate_nav', {'nodes':data, 'url_map':url_map});
					$('#navigation').append(nav_html);
					$('[data-submenu]').submenupicker();

					load_dropdownhover();
				}
			})
		}

		function load_dropdownhover(){
			$('[data-hover="dropdown"]').dropdownHover({
				delay :200
			});
		}

		function get_navigation_url(url_name){
			return url_map[url_name];
		}

		$(function () {
			load_navigation();
		});
	</script>

</body>
</html>