douban_movie/urls.py
from django.urls import path
from douban_movie.views import index, movie_detail, search_movie, to_search_list

app_name = 'douban_movie'

urlpatterns = [
	path('', index, name='index'),
	path('movie_detail', movie_detail, name='movie_detail'),
	path('movie_detail/<str:id>', movie_detail, name='movie_detail'),
	path('search_movie', search_movie, name='search_movie'),
	path('to_search_list', to_search_list, name='to_search_list'),

]

movie/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
	path('admin/', admin.site.urls),
	path('navigation/', include('navigation.urls')),
	path('douban_movie/', include('douban_movie.urls')),
	path('user/', include('user.urls')),
	path('comments/', include('django_comments.urls'))
]

user/urls.py
from django.urls import path
from user.views import to_register, register, to_login, login, logout

app_name = 'user'

urlpatterns = [
	path('to_register', to_register, name='to_register'),
	path('register', register, name='register'),
	path('to_login', to_login, name='to_login'),
	path('login', login, name='login'),
    path('logout', logout, name='logout')
]

user/models.py
from django.db import models

# Create your models here.

user/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

from user.decorators import check_login

from re import compile, match

main_page_url = 'douban_movie:index'

# Create your views here.
@check_login(False, main_page_url)
@require_GET
def to_register(request):
	return render(request, 'user/register.html')

@require_POST
def register(request):

	if request.user.is_authenticated:
		return JsonResponse({
			'fail_field' : '已登录',
			'msg' : '已登录'
		})

	fail_field, msg = check_regist(**request.POST)
	
	# 注册错误
	if fail_field:
		pass
	
	# 注册成功
	else:
		user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'], email=request.POST['email'])
		user.save()

	return JsonResponse({
		'fail_field' : fail_field,
		'msg' : msg
	})


@check_login(False, main_page_url)
@require_GET
def to_login(request):
	return render(request, 'user/login.html')

@require_POST
def login(request):

	if request.user.is_authenticated:
		return JsonResponse({
			'flag' : 'FAIL',
			'msg' : '已登录'
		})

	flag = 'FAIL'
	msg = '登录失败'


	try:
		username_email = request.POST['username_email']
		password = request.POST['password']
		user = authenticate(request, username=username_email, password=password)

		# 登录失败
		if user is None:
			print('nono')
			pass
		else:
			auth_login(request, user)
			flag, msg = 'SUCCESS', ''

	except:
		pass

	return JsonResponse({
		'flag' : flag,
		'msg' : msg
	})

def logout(request):

	auth_logout(request)
	return HttpResponseRedirect(reverse('user:to_login'))

username_pattern = compile(r'^.{5,10}$')
password_pattern = compile(r'[a-zA-Z0-9_]{8,20}')
email_pattern = compile(r'^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$')

def check_regist(**user_info):

	fail_field = 'unknowned'
	msg = '未知错误'

	print(user_info)

	try:
		if not 'username' in user_info:
			fail_field = 'username'
			msg = '用户名不能为空'
		if not 'password' in user_info:
			fail_field = 'password'
			msg = '密码不能为空'

		username = user_info['username'][0]
		password = user_info['password'][0]
		email = user_info['email'][0] if len(user_info['email'])==1 else ''

		print(match(username_pattern, username))
		print(len(User.objects.filter(username=username)))
		# 检查用户名是否合法
		if not match(username_pattern, username):
			fail_field = 'username'
			msg = '用户名需为5到10个字符'

		# 检查邮箱是否合法
		elif email and not match(email_pattern, email):
			fail_field = 'email'
			msg = '邮箱格式错误'

		elif len(User.objects.filter(username=username))>0:
			fail_field = 'username'
			msg = '已存在的用户名'

		elif email and len(User.objects.filter(email=email))>0:
			fail_field = 'email'
			msg = '已存在的邮箱'
		else:
			fail_field = ''
			msg = '成功'


	except:
		pass

	return fail_field, msg

templates/user/login.html
{% extends 'user/template.html' %}

{% block title %}用户登录{% endblock %}

{% block head %}
	{{ block.super }}
	{% load staticfiles %}
	<script type="text/javascript" src="{% static 'js/user/login.js' %}"></script>
	
{% endblock %}

{% block form %}
	<form id="login_form" action="" onsubmit="function(){return false}">
		{% csrf_token %}
		<div class="form-group row">
			<input type="text" name="username_email" placeholder="请输入用户名或邮箱" require autocomplete="off" class="form-control">
		</div>
		<div class="form-group row">
			<input type="hidden" name="password">
			<input type="password" id="password_" placeholder="请输入密码" autocomplete="off" class="form-control">
		</div>
		<div class="form-group row justify-content-end">
			<a href="{% url 'user:to_register' %}">没有账号，注册</a>
		</div>

		<div class="row justify-content-center">
			<button type="button" class="btn btn-primary col-md-4" onclick="login()">登录</button>	
		</div>
	</form>
{% endblock %}

templates/user/register.html
{% extends 'user/template.html' %}

{% block title %}用户注册{% endblock %}

{% block head %}
	{{ block.super }}
	{% load staticfiles %}
	<script type="text/javascript" src="{% static 'js/user/register.js' %}"></script>
	
{% endblock %}

{% block form %}


	<form id="register_form" action="" onsubmit="function(){return false}">
		{% csrf_token %}
		<div class="form-group row">
			<label class="col-md-3 col-form-label"><span style="color: red">*</span>用户名</label>
			<div class="col-md-9">
				<input type="text" name="username" placeholder="请输入用户名" require autocomplete="off" class="form-control">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-md-3 col-form-label"><span style="color: red">*</span>密码</label>
			<div class="col-md-9">
				<input type="hidden" name="password">
				<input type="password" id="password_" placeholder="请输入密码" autocomplete="off" class="form-control">
			</div>
		</div>
		<div class="form-group row">
			<label class="col-md-3 col-form-label">电子邮箱</label>
			<div class="col-md-9">
				<input type="email" name="email" placeholder="请输入电子邮箱" autocomplete="off" class="form-control">
			</div>
		</div>
		<div class="form-group row justify-content-end">
			<a href="{% url 'user:to_login' %}">已有账号，登录</a>
		</div>

		<div class="row justify-content-center">
			<button type="button" class="btn btn-primary col-md-4" onclick="register()">注册</button>
		</div>
		
	</form>
{% endblock %}

templates/user/template.html
{% extends 'common/template.html' %}

{% block head %}
	{% load staticfiles %}
	<script type="text/javascript" src="{% static 'js/common/sha256.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/user/common.js' %}"></script>

	<style type="text/css">
		.error_field{
			border-color: red;
		}
	</style>

{% endblock %}

{% block body%}
	
	<input type="hidden" id="to_register_url" value="{% url 'user:to_register' %}">
	<input type="hidden" id="register_url" value="{% url 'user:register' %}">
	<input type="hidden" id="to_login_url" value="{% url 'user:to_login' %}">
	<input type="hidden" id="login_url" value="{% url 'user:login' %}">
	<input type="hidden" id="main_page_url" value="{% url 'douban_movie:index' %}">

	<div class="container" >
		<div class="row align-items-center form_row" style="height: 80vh;">
			<div class="col col-md-4 offset-md-4">
				{% block form %}{% endblock %}
			</div>
		</div>
	</div>


{% endblock %}